### PR TITLE
Add PasteCommand and parse rule for `p`

### PR DESCRIPTION
**Pull request by caleb-allen**
- [x] Add PasteCommand
- [x] add parse rule for paste command
- [x] add tests for parsing `p`
- [x] add `P`
- [x] add tests for copy/paste

### CODE REVIEW

**Comment by bjarthur** [comment]
`p` and `P` would be awesome!  looking forward to this PR

**Comment by caleb-allen** [comment]
@bjarthur I'm hoping to have this in before JuliaCon! Stay tuned

**Comment by caleb-allen** [comment]
@bjarthur I still need to write up some docs and release a new package version (after the weekend, probably), but if you'd like to give it a try before then you can run off of master with `] add VimBindings#master` and then run `VimBindings.Config.system_clipboard!(true)`

**Comment by caleb-allen** [comment]
@bjarthur the clipboard feature has been released in `0.3.8`, and can be enabled using the command I provided above. See the [docs](https://caleb-allen.github.io/VimBindings.jl/v0.3.8/config/#System-Clipboard-Integration) for details

**Pull request merged**
